version: "3.7"

services:
  converter:
    container_name: mautoolz-converter
    image: mautoolz-converter
    build:
      context: .
    restart: unless-stopped

networks:
  default:
    external:
      name: caddynet
